# Generated by Django 4.0.5 on 2022-06-30 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='core.client')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'unique_together': {('client', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='№')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата')),
                ('service', models.CharField(max_length=255, verbose_name='Сервис')),
                ('fraud_score', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Детектор мошенничества')),
                ('service_class', models.IntegerField(verbose_name='Классификатор услуг: Класс')),
                ('service_name', models.CharField(max_length=255, verbose_name='Классификатор услуг: Имя')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.client', verbose_name='Клиент')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Счета организации клиента',
                'verbose_name_plural': 'Счета организации клиента',
                'unique_together': {('organization', 'number')},
            },
        ),
    ]
