# Generated by Django 4.0.5 on 2022-06-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_organization_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='fraud_weight',
            field=models.IntegerField(default=0),
        ),
    ]
